

POST http://localhost:3003/api/blogs  
Content-Type: application/json

{
  "title": "Juokse sinä humma kissa",
  "author": "Heppana",
  "url": "http://koira.fi",
  "likes": 2422
}


POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Kissa",
  "username":"Heppana",
  "password": "Hevastaa11"
}



POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Heppana",
  "password": "Hevastaa11"
}