

POST http://localhost:3003/api/blogs  
Content-Type: application/json

{
  "title": "Hepan juoksu",
  "author": "Heppa",
  "url": "http://koira.fi",
  "likes": 42
}


POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Lekka",
  "username":"eewee",
  "password": "1237"
}
